# Generated by Django 4.2.1 on 2023-05-07 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='explorerdeliveredui',
            name='itens',
        ),
        migrations.AlterField(
            model_name='explorerdeliveredui',
            name='image',
            field=models.IntegerField(),
        ),
    ]
