# Generated by Django 4.2.1 on 2023-05-07 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_explorerdeliveredui_itens_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='explorerdeliveredui',
            name='itens',
            field=models.ManyToManyField(to='app.exploreroverviewitem'),
        ),
        migrations.AlterField(
            model_name='explorerdeliveredui',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
