# Generated by Django 4.2.1 on 2023-05-07 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_explorerdeliveredui_itens_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='explorerdeliveredui',
            name='image',
            field=models.TextField(),
        ),
    ]
